# Site settings
title: Project S.H.E.D.
description: > # this means to ignore newlines until "baseurl:"
  A local multiplayer game about a spaceman looking for the meaning of life.
  One player control the spaceman, while two others control the good and evil
  forces of the universe, in this case represented as carpenters: one building
  wooden blocks to stop the spaceman and the other removing them. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://project-shed.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  project-shed

# Build settings
markdown: kramdown
